### PR TITLE
fix: transaction state 'resets'

### LINKED ISSUE #1091: Transaction state 'resets'
If you keep the 'Transaction confirmed' modal open after performing a transaction, the transaction state will reset when the token prices are refetched again.

add-breaks

### PR DESCRIPTION
**Pull request by groninge01**
fixes #1091

### CODE REVIEW

File: lib/modules/swap/modal/SwapModal.tsx [hunk 1]
```diff
@@ -35,6 +37,7 @@ export function SwapPreviewModal({
   const { isDesktop } = useBreakpoints()
   const initialFocusRef = useRef(null)
   const { userAddress } = useUserAccount()
+  const { stopPolling } = useTokens()
```
[the remark this answers is not in the document]
Comment (groninge01) [reply lib/modules/swap/modal/SwapModal.tsx:40]: Renamed

File: lib/modules/tokens/TokensProvider.tsx [hunk 2]
```diff
@@ -31,24 +31,27 @@ export function _useTokens(
...
-      pollInterval: mins(3).toMs(),
-      notifyOnNetworkStatusChange: true,
-    }
-  )
+  const {
+    data: tokenPricesData,
+    loading: isLoadingTokenPrices,
+    startPolling: startTokenPricePolling,
+    stopPolling: stopTokenPricePolling,
+  } = useQuery(GetTokenPricesDocument, {
```
Comment (garethfuller) [inline lib/modules/tokens/TokensProvider.tsx:46]: Lets not export the polling interval as well since it's internal context. We can do this instead:
```suggestion
    startPolling,
    stopPolling,
  } = useQuery(GetTokenPricesDocument, {

const startTokenPricePolling = () => startPolling(pollInterval)
const stopTokenPricePolling = () => stopPolling(pollInterval)
```
And export those.

**Review by garethfuller — CHANGES_REQUESTED** [review]

File: lib/modules/tokens/TokensProvider.tsx (hunk 2 above)
Comment (groninge01) [reply lib/modules/tokens/TokensProvider.tsx]: Updated this.

**Review by garethfuller — APPROVED** [review]
